# Some Examples

## Converting multiple columns to proportions

```{r, warning=FALSE, message=FALSE}
library(data.table)

dt <- data.table(
  ID = 1:3,
  var1 = c(2, 4, 1),
  var2 = c(3, 1, 2),
  var3 = c(5, 0, 3),
  var4 = c(0, 2, 1),
  var5 = c(0, 1, 3)
)

dt[, total := rowSums(.SD), .SDcols = var1:var5]

# this works
(new_dt <- dt[, lapply(.SD, function(x) x / total),
   .SDcols = var1:var5, by = c('ID', 'total')][, c(1, 3:7 ,2), with = FALSE])

# this works
vars <- paste0("var", 1:5)
dt[, (vars) := lapply(.SD, function(x) x / total),
    .SDcols = var1:var5][]

# the following does not work
# dt[, (var1:var5) := lapply(.SD, function(x) x / total),
#    .SDcols = var1:var5]


```

## Find number of unique x-y coordiates in each group

```{r}
set.seed(1234)
dt <- data.table(mb = sample(letters[1:3], size = 100, replace = TRUE),
                 x = sample(1:9, size = 100, replace = TRUE),
                 y = sample(1:9, size = 100, replace = TRUE))
dt[, x_y := paste0(x, '_', y)][, uniqueN(x_y), by = mb][order(mb)][]
dt[, new_x_y := paste0('(', x, ', ',  y, ')')][, uniqueN(new_x_y), by = mb][order(mb)][]
dt[, .(n = uniqueN(paste0(x, '_', y))), by = mb][order(mb)][]
```


## Take a sample of rows

```{r, warning=FALSE, message=FALSE}
library(data.table)

n <- 3
dt <- data.table(x = 1:10, y = rnorm(10))
dt[sample(.N, size = n)][]
```


## Stratified random sampling

```{r}
library(data.table)

set.seed(123)
f_dt <- data.table(ID = sample(letters[1:3], 100, replace = TRUE))

sample_sizes <- c(a = 5, b = 10, c = 18)
f_dt[, sample_indi := sampling::srswor(n = sample_sizes[[ID[1]]], N = .N), by = ID]

# check
f_dt[sample_indi == 1, .N, by = ID][order(ID)][]
```

## Two pairs of square brackets vs. one pair of square brackets

**Notice the difference between `dt_1` and `dt_2`**

```{r, message=FALSE, warning=FALSE}
library(data.table)

set.seed(123456)
(dt <- data.table(x = sample(letters[1:3], 10, replace = TRUE)))

print(dt_1 <- dt[x == 'a'][, y := 1])

print(dt_2 <- copy(dt)[x == 'a', y := 1])
```

